[project]
name = "fence-magalucloud"
version = "0.1.0"
description = "Magalu Cloud Pacemakers Cluster Fence"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "danielsabatini" }]
keywords = []

dependencies = [
  "requests>=2.28",
]

[project.scripts]
fence-magalucloud     = "fence_magalucloud.fence_magalucloud:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/fence_magalucloud"]

[tool.ruff]
target-version = "py311"
line-length = 100
src = ["src", "tests"]
exclude = ["build", "dist", "__pycache__", "*.egg-info", ".venv", "src/fence_magalucloud/fencing.py"]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "PL", "PT"]
ignore = ["PLR0913"]

[tool.ruff.lint.per-file-ignores]
"tests/unit/**/*.py" = ["PLR2004", "PT012"]
"tests/integration/**/*.py" = ["PLR2004", "PT011"]

[tool.ruff.format]
quote-style = "single"

[tool.pyright]
pythonVersion = "3.11"
typeCheckingMode = "basic"
include = ["src", "tests"]
extraPaths = ["src"]
exclude = ["build", "dist", "**/__pycache__", "**/*.egg-info", ".venv", "src/fence_magalucloud/fencing.py"]
venvPath = "."
venv = ".venv"
reportMissingImports = "none"
reportMissingModuleSource = "none"
reportOptionalMemberAccess = "none"

[tool.pytest.ini_options]
testpaths = ["tests/unit", "tests/integration"]
addopts = "--cov=src --cov-report=xml --cov-report=term --cov-report=html -vv --cov-config=pyproject.toml"

[tool.coverage.run]
omit = ["*/fencing.py"]

[dependency-groups]
dev = [
    "ruff",
    "pytest",
    "pytest-cov",
    "pyright",
    "pyinstaller"
]