sonar.projectKey=fence-magalucloud
sonar.projectName=fence-magalucloud
sonar.projectVersion=0.1.0

sonar.host.url=http://localhost:9000/

sonar.language=python
sonar.python.version=3.11

sonar.sources=src/fence_magalucloud

sonar.tests=tests

sonar.test.inclusions=tests/**/*

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**, **/*.pdf, **/*.xlsx, **/*.csv, setup.py, .venv/**, notes.txt, src/fence_magalucloud/fencing.py
sonar.token=${env:SONAR_TOKEN}
